"use client";
import { useMemo, useState } from "react";
type Engine="openai"|"gemini"; type Stage=1|2|3; type Style="official"|"executive"|"action"; type Length="brief"|"standard"|"detailed";
const ENGINES={openai:{name:"OpenAI · Luna",model:"gpt-5-mini"},gemini:{name:"Gemini · 3.5 Flash-Lite",model:"gemini-2.5-flash-lite"}};
const PROMPT="당신은 한국어 평가위원회 회의록 작성자입니다. 전사문에 명시된 사실만 사용하고 추정하지 마세요. 확인되지 않은 값은 미확인으로 표시하세요. 제목, 회의 개요, 참석자, 안건 및 진행 순서, 주요 논의 내용, 결정사항 및 평가 결과, 조건 및 액션아이템, 미해결 사항·확인 필요 사항을 Markdown으로 작성하세요. 위원별 의견과 최종 의결을 구분하고 평가등급·지원금액·조건·담당자·기한을 보존하세요.";
function md(s:string){return s.split("\n").map((l,i)=>{const k=i+l;if(l.startsWith("# "))return <h2 key={k}>{l.slice(2)}</h2>;if(l.startsWith("## "))return <h3 key={k}>{l.slice(3)}</h3>;if(l.startsWith("### "))return <h4 key={k}>{l.slice(4)}</h4>;if(l.startsWith("- "))return <li key={k}>{l.slice(2)}</li>;if(/^\d+\. /.test(l))return <li className="numbered" key={k}>{l.replace(/^\d+\. /,"")}</li>;if(l.startsWith("> "))return <blockquote key={k}>{l.slice(2)}</blockquote>;if(!l.trim())return <div className="markdown-spacer" key={k}/>;return <p key={k}>{l}</p>})}
async function docx(f:File){const b=new Uint8Array(await f.arrayBuffer());const t=new TextDecoder();const x=t.decode(b);const m=[...x.matchAll(/<w:t[^>]*>([\s\S]*?)<\/w:t>/g)].map(a=>a[1].replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">"));if(!m.length)throw Error("DOCX 본문을 읽지 못했습니다.");return m.join(" ")}
export default function Home(){const [stage,setStage]=useState<Stage>(1),[engine,setEngine]=useState<Engine>("openai"),[key,setKey]=useState(""),[file,setFile]=useState<File|null>(null),[text,setText]=useState(""),[style,setStyle]=useState<Style>("official"),[len,setLen]=useState<Length>("standard"),[result,setResult]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
const canInput=!!key.trim()&&!!text.trim();const rendered=useMemo(()=>result?md(result):null,[result]);
async function choose(f:File|null){setFile(f);setError("");if(!f)return setText("");try{setText(f.name.endsWith(".docx")?await docx(f):await f.text())}catch(e){setError(e instanceof Error?e.message:"파일을 읽지 못했습니다.")}}
async function run(){if(!canInput)return;setBusy(true);setError("");try{const styleText={official:"공식 평가회의 격식체",executive:"임원 보고용 핵심 결론 중심",action:"담당자·기한 중심 실행체"}[style];const lenText={brief:"간결하게 1~2페이지",standard:"논의와 근거를 균형 있게",detailed:"발언 맥락까지 상세하게"}[len];const prompt= PROMPT+"\n문체: "+styleText+"\n분량: "+lenText+"\n--- 전사문 ---\n"+text;let r:Response,o="";if(engine==="openai"){r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+key.trim()},body:JSON.stringify({model:ENGINES[engine].model,input:prompt})});const d=await r.json();o=d.output_text||"";if(!r.ok)throw Error(d.error?.message||"OpenAI API 요청에 실패했습니다.")}else{r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/"+ENGINES[engine].model+":generateContent?key="+encodeURIComponent(key.trim()),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}]})});const d=await r.json();o=d.candidates?.[0]?.content?.parts?.map((p:{text?:string})=>p.text||"").join("\n")||"";if(!r.ok)throw Error(d.error?.message||"Gemini API 요청에 실패했습니다.")}if(!o.trim())throw Error("요약 결과가 비어 있습니다.");setResult(o.trim());setStage(3)}catch(e){setError(e instanceof Error?e.message:"요약 중 오류가 발생했습니다.")}finally{setBusy(false)}}
function download(){const a=document.createElement("a"),u=URL.createObjectURL(new Blob([result],{type:"text/markdown"}));a.href=u;a.download=(file?.name.replace(/\.[^.]+$/,"")||"회의록")+"_회의록.md";a.click();URL.revokeObjectURL(u)}
const step=(n:Stage,t:string)=><button className={stage===n?"current":stage>n?"done":""} onClick={()=>n<=stage&&setStage(n)}><span>0{n}</span>{t}{n<3&&<b>→</b>}</button>;
return <main className="site-shell"><header className="topbar"><div className="brand"><span className="brand-mark">M</span>Minutes Lab</div><span className="topbar-note">회의 전사문을 실무 회의록으로</span></header><section className="hero"><div className="eyebrow"><span/> AI MEETING NOTES</div><h1>회의 전사문을<br/><em>결정 가능한 기록</em>으로.</h1><p>입력하고, 다듬고, 결과를 가져가세요.<br/>회의록 작성의 흐름을 세 화면으로 단순하게 만들었습니다.</p></section><nav className="stepper">{step(1,"Input")}{step(2,"Process")}{step(3,"Output")}</nav>
{stage===1&&<section className="stage-panel"><div className="stage-heading"><span className="stage-kicker">STEP 01 · INPUT</span><h2>회의의 재료를 넣어주세요.</h2><p>API 키와 모델 설정, 파일 또는 전사문 전문을 입력합니다.</p></div><div className="input-grid"><div className="control-card"><h3>전사문 파일</h3><label className={"dropzone "+(file?"has-file":"")} htmlFor="file"><input id="file" type="file" accept=".docx,.txt,.md" onChange={e=>choose(e.target.files?.[0]||null)}/><span className="upload-icon">↥</span><strong>{file?file.name:"파일을 끌어놓거나 클릭하세요"}</strong><small>{file?"읽기 완료 · "+text.length.toLocaleString()+"자":".docx, .txt, .md 지원"}</small></label></div><div className="control-card"><h3>API 키와 엔진</h3><div className="engine-toggle">{(Object.keys(ENGINES) as Engine[]).map(k=><button key={k} className={engine===k?"selected":""} onClick={()=>setEngine(k)}>{ENGINES[k].name}<span className="radio-dot"/></button>)}</div><label className="field-label">API 키</label><div className="key-field"><input type="password" placeholder={engine==="openai"?"sk-...":"AIza..."} value={key} onChange={e=>setKey(e.target.value)}/><span>저장 안 함</span></div></div></div><div className="control-card transcript-card"><div className="card-title-row"><h3>또는 전사문 전문 붙여넣기</h3>{text&&<span className="ready-label">{text.length.toLocaleString()}자 준비 완료</span>}</div><textarea value={text} onChange={e=>{setText(e.target.value);setFile(null)}} placeholder="회의 전사문을 여기에 붙여넣으세요..."/></div>{error&&<div className="error-banner">{error}</div>}<div className="stage-actions"><span>키와 전사문은 브라우저에서만 사용됩니다.</span><button className="primary-button" disabled={!canInput} onClick={()=>setStage(2)}>다음: 요약 설정 →</button></div></section>}
{stage===2&&<section className="stage-panel"><div className="stage-heading"><span className="stage-kicker">STEP 02 · PROCESS</span><h2>어떤 회의록으로 만들까요?</h2><p>목적에 맞는 문체와 분량을 선택하면 결과에 반영됩니다.</p></div><div className="settings-grid">{[["style","요약 스타일",[["official","공식 평가회의","격식체 · 결정사항 중심"],["executive","임원 보고용","핵심 결론 · 빠른 검토"],["action","실행 관리용","담당자 · 기한 · 액션 강조"]]],["len","출력 분량",[["brief","간결하게","핵심만 1~2페이지"],["standard","표준","논의와 근거를 균형 있게"],["detailed","상세하게","발언 맥락까지 빠짐없이"]]]].map(([kind,title,opts])=><div className="control-card" key={kind as string}><h3>{title as string}</h3><div className="option-list">{(opts as string[][]).map(([v,t,d])=><button key={v} className={((kind==="style"?style:len)===v)?"option selected":"option"} onClick={()=>kind==="style"?setStyle(v as Style):setLen(v as Length)}><span className="option-radio"/><span><strong>{t}</strong><small>{d}</small></span></button>)}</div></div>)}</div><div className="process-note"><span>✦</span><div><strong>자동 추출 항목</strong><p>평가등급, 지원금액, 선정 조건, 제출기한, 담당자와 최종 의결을 우선적으로 보존합니다.</p></div></div>{error&&<div className="error-banner">{error}</div>}<div className="stage-actions"><button className="secondary-button" onClick={()=>setStage(1)}>← 이전</button><button className="primary-button" disabled={busy} onClick={run}>{busy?"회의록을 정리하고 있습니다…":"회의록 생성하기 →"}</button></div></section>}
{stage===3&&<section className="stage-panel output-panel"><div className="stage-heading"><span className="stage-kicker">STEP 03 · OUTPUT</span><h2>회의록이 준비되었습니다.</h2><p>내용을 검토하고 Markdown 파일로 가져가세요.</p></div><div className="result-card active"><div className="result-header"><div><span className="result-kicker">FINAL REPORT</span><h3>{file?.name.replace(/\.[^.]+$/,"")||"회의록"}</h3></div><div className="result-tools"><button onClick={()=>navigator.clipboard?.writeText(result)}>복사</button><button className="download-button" onClick={download}>↓ Markdown 다운로드</button></div></div><article className="markdown-result">{rendered}</article></div><div className="stage-actions"><button className="secondary-button" onClick={()=>setStage(2)}>← 설정 수정</button><button className="primary-button" onClick={download}>보고서 다운로드 ↓</button></div></section>}<footer><span>Minutes Lab</span><span>실무자의 시간을 아끼는 회의 기록</span></footer></main>}
